image: gradle:jdk11

before_script:
  - chmod +x gradlew

stages:
  - build
  - test

build:
  stage: build
  script: ./gradlew build -x test
  artifacts:
    paths:
      - build/libs/*.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle check
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
      
after_script:
  - echo "End CI"